version: '2'
services:
    web:
       network_mode: "bridge"
       image: "shfew332132/springboot-login-log4j2:latest"
       ports:
            - "9090:9090"
       depends_on:
            - mysql
    
    mysql:
        network_mode: "bridge"
        environment:
            MYSQL_ROOT_PASSWORD: "123456"
            MYSQL_USER: 'test'
            MYSQL_PASS: '123456'
        image: "mysql:5.7"
        restart: always
        volumes:
            - "./db:/var/lib/mysql"
            - "./conf/my.cnf:/etc/my.cnf"
            - "./init:/docker-entrypoint-initdb.d/"
        ports:
            - "3306:3306"
